services:
  nixfastapi:
    container_name: nixfastapi-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7999:7999
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/curl", "-f", "http://0.0.0.0:7999/health"]
    tty: true
    stdin_open: true
    networks:
      - default

networks:
  default:
    name: nixfastapi-network
    external: false
